user = 100
run-time = 3m
spawn-rate = 5
headless = true
locustfile = ./scenarios/grpc/gateway/new_user_issue_physical_card/scenario.py
html = ./scenarios/grpc/gateway/new_user_issue_physical_card/report.html
